# Generated by Django 4.2.7 on 2024-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='link2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link3',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link4',
            field=models.URLField(blank=True),
        ),
    ]
